version: "2"
services:
  bos_swoole:
    image: manaphp/php73:3.0
    volumes:
      - /etc/localtime:/etc/localtime
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/bos/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/bos/tmp:/var/www/html/tmp
      - /data/volumes/${COMPOSE_PROJECT_NAME}/bos/uploads:/var/www/html/public/uploads
    command: php /var/www/html/public/index.php
    restart: always
  bos_nginx:
    image: nginx:1.17.6
    volumes:
      - /etc/localtime:/etc/localtime
      - ../:/var/www/html
      - ./nginx/conf/nginx.conf.swoole:/etc/nginx/nginx.conf
      - /data/volumes/${COMPOSE_PROJECT_NAME}/bos/uploads:/var/www/html/public/uploads
      - /data/volumes/${COMPOSE_PROJECT_NAME}/bos/nginx:/var/log/nginx
    ports:
      - 8185:80
    restart: always